# Generated by Django 3.0.3 on 2020-02-10 11:26

import digitalbeti.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[], max_length=100)),
                ('city', models.CharField(blank=True, choices=[], max_length=100)),
                ('district', models.CharField(blank=True, choices=[], max_length=100)),
                ('village', models.CharField(blank=True, choices=[], max_length=100)),
                ('text', models.CharField(blank=True, max_length=250, verbose_name='Full Address')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.CharField(max_length=1000)),
                ('option_2', models.CharField(max_length=1000)),
                ('option_3', models.CharField(max_length=1000)),
                ('option_4', models.CharField(max_length=1000)),
                ('order', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalbeti.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('data', models.CharField(max_length=1000)),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalbeti.Question')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalBetiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('USER', 'User'), ('VLE', 'Village Level Entrepreneur'), ('DM/DC', 'DM/DC'), ('STATE', 'States'), ('ADMIN', 'Admin')], max_length=100)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalbeti.DigitalBetiUser')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('fathers_name', models.CharField(max_length=120)),
                ('fathers_occupation', models.CharField(max_length=120)),
                ('mothers_name', models.CharField(max_length=120)),
                ('mothers_occupation', models.CharField(max_length=120)),
                ('gender', models.IntegerField(choices=[(1, 'Female')], default=1)),
                ('date_of_birth', models.DateField(validators=[digitalbeti.models.CustomValidators.validate_date_of_birth])),
                ('email_id', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=13)),
                ('family_annual_income', models.IntegerField(choices=[(0, 'Upto 300,000'), (1, 'Between 300,000 to 500,000'), (2, '500,000+')], default=0)),
                ('language_pref_1', models.CharField(choices=[('NA', 'Not Applicable'), ('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Bodo', 'Bodo'), ('Dogri', 'Dogri'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Manipuri', 'Manipuri'), ('Marathi', 'Marathi'), ('Nepali', 'Nepali'), ('Oriya', 'Oriya'), ('Punjabi', 'Punjabi'), ('Sanskrit', 'Sanskrit'), ('Santhali', 'Santhali'), ('Sindhi', 'Sindhi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='Hindi', max_length=30, verbose_name='First Language Preference')),
                ('language_pref_2', models.CharField(choices=[('NA', 'Not Applicable'), ('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Bodo', 'Bodo'), ('Dogri', 'Dogri'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Manipuri', 'Manipuri'), ('Marathi', 'Marathi'), ('Nepali', 'Nepali'), ('Oriya', 'Oriya'), ('Punjabi', 'Punjabi'), ('Sanskrit', 'Sanskrit'), ('Santhali', 'Santhali'), ('Sindhi', 'Sindhi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='NA', max_length=30, verbose_name='Second Language Preference')),
                ('language_pref_3', models.CharField(choices=[('NA', 'Not Applicable'), ('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Bodo', 'Bodo'), ('Dogri', 'Dogri'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Manipuri', 'Manipuri'), ('Marathi', 'Marathi'), ('Nepali', 'Nepali'), ('Oriya', 'Oriya'), ('Punjabi', 'Punjabi'), ('Sanskrit', 'Sanskrit'), ('Santhali', 'Santhali'), ('Sindhi', 'Sindhi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='NA', max_length=30, verbose_name='Third Language Preference')),
                ('education_qualification', models.CharField(choices=[('PG', 'Post Graduate'), ('G', 'Graduate'), ('10+', '10+'), ('-10', 'Below 10 Standard')], default='10+', max_length=50)),
                ('differently_abled', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you differently abled?')),
                ('bank_account', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Do you have a bank account?')),
                ('permanent_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent', to='digitalbeti.Address')),
                ('temporary_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary', to='digitalbeti.Address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalbeti.DigitalBetiUser')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('ref_hash', models.CharField(default=digitalbeti.models.generate_random_string, max_length=16, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='STARTED', max_length=10)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('answers', models.CharField(max_length=200)),
                ('current_question_id', models.IntegerField(default=-1)),
                ('score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalbeti.Exam')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalbeti.DigitalBetiUser')),
            ],
        ),
    ]
