# Generated by Django 3.0.3 on 2020-02-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0004_auto_20200212_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalbetiuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='digitalbetiuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='digitalbetiuser',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
