# Generated by Django 3.0.3 on 2020-02-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0006_auto_20200213_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiarydata',
            name='family_annual_income',
        ),
        migrations.RemoveField(
            model_name='beneficiarydata',
            name='temporary_address',
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='vle_csc_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VLE CSC ID'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='education_qualification',
            field=models.CharField(choices=[('PG', 'Post Graduate and Above'), ('G', 'Graduate'), ('12', '12'), ('10', '10'), ('-10', 'Below 10')], default='10+', max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='email_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
