# Generated by Django 3.0.3 on 2020-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0007_auto_20200215_0749'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='villagedetails',
            name='village_detail',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='subdistrict',
        ),
        migrations.RenameField(
            model_name='digitalbetiuser',
            old_name='city',
            new_name='subdistrict',
        ),
        migrations.RenameField(
            model_name='villagedetails',
            old_name='city',
            new_name='subdistrict',
        ),
        migrations.AddConstraint(
            model_name='villagedetails',
            constraint=models.UniqueConstraint(fields=('state', 'district', 'subdistrict', 'village'), name='village_detail'),
        ),
    ]
