# Generated by Django 3.0.3 on 2020-02-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0008_auto_20200215_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('JAMMU AND KASHMIR', 'JAMMU AND KASHMIR'), ('TELANGANA', 'TELANGANA'), ('TAMIL NADU', 'TAMIL NADU'), ('CHHATTISGARH', 'CHHATTISGARH'), ('BIHAR', 'BIHAR'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('BIHAR', 'BIHAR'), ('KERALA', 'KERALA'), ('MAHARASHTRA', 'MAHARASHTRA'), ('RAJASTHAN', 'RAJASTHAN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='subdistrict',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='village',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='education_qualification',
            field=models.CharField(choices=[('-10', 'Below 10th'), ('10', '10th (High School)'), ('12', '12th (Intermediate)'), ('G', 'Graduate'), ('PG', 'Post Graduate and Above')], default='10+', max_length=50),
        ),
    ]
