# Generated by Django 3.0.3 on 2020-02-20 06:38

import digitalbeti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0009_auto_20200218_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('JAMMU AND KASHMIR', 'JAMMU AND KASHMIR'), ('TELANGANA', 'TELANGANA'), ('TAMIL NADU', 'TAMIL NADU'), ('CHHATTISGARH', 'CHHATTISGARH'), ('BIHAR', 'BIHAR'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('BIHAR', 'BIHAR'), ('KERALA', 'KERALA'), ('MAHARASHTRA', 'MAHARASHTRA'), ('RAJASTHAN', 'RAJASTHAN')], max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='subdistrict',
            field=models.CharField(max_length=100, verbose_name='Subdistrict'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village',
            field=models.CharField(max_length=100, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='date_of_birth',
            field=models.DateField(validators=[digitalbeti.models.CustomValidators.validate_date_of_birth], verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='education_qualification',
            field=models.CharField(choices=[('-10', 'Below 10th'), ('10', '10th (High School)'), ('12', '12th (Intermediate)'), ('G', 'Graduate'), ('PG', 'Post Graduate and Above')], default='10+', max_length=50, verbose_name='Education qualification'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='email_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='fathers_name',
            field=models.CharField(max_length=120, verbose_name='Father name'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='mothers_name',
            field=models.CharField(max_length=120, verbose_name='Mother name'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='personal_monthly_income',
            field=models.IntegerField(choices=[(0, '0-10,000'), (1, '10,000-20,000'), (2, '20,000+')], default=0, verbose_name='Personal monthly income'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='villagedetails',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='villagedetails',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='villagedetails',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
