# Generated by Django 3.0.3 on 2020-02-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0009_auto_20200216_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('JAMMU AND KASHMIR', 'JAMMU AND KASHMIR'), ('TELANGANA', 'TELANGANA'), ('TAMIL NADU', 'TAMIL NADU'), ('CHHATTISGARH', 'CHHATTISGARH'), ('BIHAR', 'BIHAR'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('KERALA', 'KERALA'), ('MAHARASHTRA', 'MAHARASHTRA'), ('RAJASTHAN', 'RAJASTHAN')], max_length=100),
        ),
        migrations.CreateModel(
            name='VLECompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000, verbose_name='Facebook Profile Link')),
                ('current_likes', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalbeti.DigitalBetiUser')),
            ],
        ),
    ]
