# Generated by Django 3.0.3 on 2020-02-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0010_auto_20200216_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalbetiuser',
            name='prr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='digitalbetiuser',
            name='state',
            field=models.CharField(choices=[('JAMMU AND KASHMIR', 'JAMMU AND KASHMIR'), ('TELANGANA', 'TELANGANA'), ('TAMIL NADU', 'TAMIL NADU'), ('CHHATTISGARH', 'CHHATTISGARH'), ('BIHAR', 'BIHAR'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('KERALA', 'KERALA'), ('MAHARASHTRA', 'MAHARASHTRA'), ('RAJASTHAN', 'RAJASTHAN')], max_length=100, null=True),
        ),
    ]
