# Generated by Django 3.0.3 on 2020-02-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0010_auto_20200220_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagedetails',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='villagedetails',
            name='subdistrict',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='villagedetails',
            name='village',
            field=models.CharField(max_length=100),
        ),
    ]
