# Generated by Django 3.0.3 on 2020-03-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0012_auto_20200326_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='urls_bn',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='urls_en',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='urls_hi',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='urls_kn',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='urls_ml',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='urls_mr',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='urls_or',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='urls_te',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='urls_ur',
        ),
    ]
