# Generated by Django 3.0.4 on 2020-05-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbeti', '0014_auto_20200430_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarydata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalbeti.DigitalBetiUser'),
        ),
    ]
